name       : python-pyproject-hooks
version    : 1.0.0
release    : 1
source     :
    - https://github.com/pypa/pyproject-hooks/archive/refs/tags/v1.0.0.tar.gz : d45c52f9af6bce94755eecf9dbfe6b3c89ef9a50088a8809f5bbec4ed0f9be0b
license    : GPL-2.0-or-later # CHECK ME
component  : MIT
summary    : A low-level library for calling build-backends in `pyproject.toml`-based project
description: |
    This is a low-level library for calling build-backends in pyproject.toml-based project. It provides the basic functionality to help write tooling that generates distribution files from Python projects. If you want a tool that builds Python packages, you'll want to use https://github.com/pypa/build instead. This is an underlying piece for pip, build and other "build frontends" use to call "build backends" within them.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
